# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-10-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('seatInfo', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
