# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-10-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_table', django_mysql.models.JSONField(default=dict)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.Screens', unique=True)),
            ],
        ),
    ]
